- hosts: localhost
  become: no
  pre_tasks:
    - name: update brew
      become: no
      changed_when: False
      homebrew: 
        update: True
  tasks:
    - import_tasks: tasks/alacritty-setup.yml
